name: Python CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          pip install pytest
      
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            python -m pytest tests/ -v
          else
            echo "::warning::No tests directory found"
            exit 0
          fi

  deploy:
    runs-on: self-hosted
    needs: test
    if: success()
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Docker and configure permissions
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl enable --now docker
          
          # Add current user to docker group
          sudo usermod -aG docker $USER
          
          # Fix socket permissions (temporary until reboot)
          sudo chmod 666 /var/run/docker.sock
          
          # Verify installation
          docker --version
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Set up Docker Buildx with proper permissions
        run: |
          # Create builder instance with sudo
          sudo docker buildx create --name mybuilder --use
          sudo docker buildx inspect --bootstrap
      
      - name: Build and push Docker image
        run: |
          sudo docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:latest \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:${{ github.sha }} \
            --push .
