name: Python CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi
          pip install pytest
      
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            python -m pytest tests/ -v
          else
            echo "::warning::No tests directory found"
            exit 0

  deploy:
    runs-on: self-hosted
    needs: test
    if: success()
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Set up Docker Buildx builder
        run: |
          docker buildx create --use --name mybuilder || docker buildx use mybuilder
          docker buildx inspect --bootstrap
          docker buildx ls
      
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:latest \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/python-app:${{ github.sha }} \
            --push .
